- name: fetch node.js source
  get_url: url=http://nodejs.org/dist/node-latest.tar.gz dest=/tmp/

- name: unpack node.js tarball
  command: tar zxf node-latest.tar.gz chdir=/tmp

- name: lookup directory name
  shell: ls /tmp | grep node-v
  register: node_dir

- name: configure
  shell: /usr/bin/python ./configure --prefix=/usr/local chdir=/tmp/{{ node_dir.stdout }}

- name: make
  shell: /usr/bin/make chdir=/tmp/{{ node_dir.stdout }}

- name: make install
  shell: /usr/bin/make install chdir=/tmp/{{ node_dir.stdout }}